name: gHub
version: '1.0'
main: com.Gomania.gHub.GHub
api-version: '1.21'
depends: [ProtocolLib]
softdepend: [PlaceholderAPI]

commands:
  ghub:
    description: Основная команда для управления gHub
    usage: /ghub [reload|spawn]
    permission: ghub.use
permissions:
  ghub.use:
    description: Доступ к команде /ghub
    default: true
  ghub.reload:
    description: Перезагрузка конфига gHub
    default: op
  ghub.spawn:
    description: Установка спавна gHub
    default: op
